# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cc8dde0075670fdc8a8d91d7d6b68b8cc898669ec60f6341c9c21384d93303881a06e128be0b66a590e3ce3d25d918756a8653e4a5ec1f8d3ce4c35579e6d68d
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_scret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  aws_region: <%= ENV["AWS_REGION"] %>
  aws_bucket: <%= ENV["AWS_BUCKET"] %>
  facebook_app_id: <%= ENV["FACEBOOK_API_ID"] %>
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>

test:
  secret_key_base: 413497e31e4e1f8ba8847e0ab05e58990df0bdd0d46e8109450a083b8f7ed2de124413dc0abed96dd58e422222a4f87dffda77d2eea1c2c0a57c1701516402d3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
